### ISSUE TITLE
Missing code of scheduling algorithms

### ISSUE THREAD

**Issue by xmzzyo** [S-Lab-System-Group/ChronusArtifact#1]
Hi Authors,

Thanks for your great efforts on this impressive work. But I did not find the code of compared scheduling algorithms under `alg/scheduler/` folder, which seems should be supported (in `run/exp_cluster/batch_run.sh`).

Can you please provide these baseline codes? 

Thanks!

**Comment by gaow0007** [comment]
Thanks for your interest in this work. We are currently developing a benchmark for existing DL schedulers. This still requires half of year based my expectation. We will try our best to release this benchmark **at the end of this year**. This benchmark will contain a full suite of Chronus and corresponding baselines as well as other well-known DL schedulers.

**Comment by xmzzyo** [comment]
Thanks for your reply. That sounds will be an amazing project, and I'm looking forward to your benchmark for DL schedulers.
